### ISSUE TITLE
[BUG] Administrator not getting email

### ISSUE THREAD

**Issue by Jesse-Swafford** [thewpsquad/squad-modules#2]
## Bug Description
When a customer purchases a ticket from an event the administrator does not get the PDF email even though it been selected to do so.

## Steps to Reproduce
1.Purchase a ticket from event from calendar
2.
3.

## Expected Behavior
It should email customer and administrator of the ticket sold

## Actual Behavior
Only customer is getting ticket

## Environment
- Divi Squad Version: latest version
- Divi Theme Version: latest version
- WordPress Version: latest version
- PHP Version: latest version

## Browser Information (if applicable)
- Browser: [e.g., Chrome, Firefox, Safari]
- Version:

**Comment by mralaminahamed** [comment]
Hello @Jesse-Swafford,

Thank you for reporting this issue. We appreciate your detailed description of the problem. However, I'd like to clarify that the **Divi Squad** plugin doesn't include any event calendar or ticket-selling functionality. It seems there might be some confusion about the plugin's features.

Could you please provide more information about:

1. The specific feature or module of Divi Squad you're using that should trigger an email to the administrator?

2. The exact steps you're taking within the Divi Squad plugin that should result in an email being sent?

3. The exact versions of:
   - Divi Squad plugin
   - Divi Theme
   - WordPress
   - PHP

4. Are you using any other plugins for event management or ticket sales? If so, which ones?

5. Have you checked the spam folder of the administrator's email account?

6. Can you verify that the administrator's email address is correctly set in WordPress (Settings > General)?

7. Are there any error messages in the WordPress debug log related to email sending?

8. Can you confirm that other WordPress emails (such as password reset emails) are being received by the administrator?

To help us diagnose any potential issues with email sending, please enable WordPress debug mode by adding the following to your wp-config.php file:

```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
```

After enabling debug mode, try to reproduce the issue and then check the debug.log file in the wp-content directory for any relevant error messages.

Once we have this additional information, we'll be better equipped to understand the issue you're experiencing and provide appropriate assistance. Thank you for your patience and cooperation.
